### ISSUE TITLE
Unarchive the repository

### ISSUE THREAD

**Issue by celeron533** [shadowsocks/Shadowsocks-Net#8]
@ohsorry created the .Net Core version of Shadowsocks with newly designed architect. This new born repository provides a lot of possibilities to the community and should not be archived.

**Comment by ohsorry** [comment]
I temporarily archived it because you haven't been online. 
Do you have any plans on this project? should it continue to be developed?

**Comment by celeron533** [comment]
Please go ahead. Following official Shadowsocks protocol and standards. This project is parallel to Shadowsocks-windows.
I could also assist to create a code-of-conduct to let others to contribute to the project.

**Comment by ohsorry** [comment]
Please take the time to see if the project meets standards and protocols. 
I don't really agree with the "plugin" part described [here](http://shadowsocks.org/en/spec/Plugin.html). 
but I guess you can still configure and use it as an existing "plugin" way, although it's not necessary at all with the newly designed [architecture](https://github.com/shadowsocks/Shadowsocks-Net#obfuscation-support).

What do you mean by "parallel to Shadowsocks-windows", I plan to release versions for multi-platform, not just for Windows.

**Comment by ohsorry** [comment]
> I could also assist to create a code-of-conduct 

That will be good.

**Comment by celeron533** [comment]
> don't really agree with the "plugin" part

The "plugin" provides a more flexible way to act like a "proxy chain". For instance, if there is a new software called `mcptun` could tunneling network stream in a different way, the "plugin" mechanism could handle it easily, especially it is not `IClientFilter` available.

**Comment by celeron533** [comment]
> I plan to release versions for multi-platform, not just for Windows.

Wow, that's even better!
But please do not dedicate all your time on it. Human is not machine, you need rest and sleep.

**Comment by ohsorry** [comment]
If the main function of a "plugin" is tunneling, then it is no longer the responsibility of Shadowsocks, you can call it a third party tunnel.
With Shadowsocks-Net you can integrate a less complicated tunnel（I guess it is called "SIP003"）by just one or two classes.
Actually, with Shadowsocks-Net you needn't code too much to accomplish a new feature. 
It's fun, I will finish it in my spare time.

**Comment by ohsorry** [comment]
Take some time to contribute to this project. 😉
